version: '3'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=odevtube
      - DB_PASSWORD=odevtube_password
      - DB_NAME=odevtube
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=odevtube
      - MYSQL_USER=odevtube
      - MYSQL_PASSWORD=odevtube_password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
